trigger:
- master

pool:
  name: 'DESKTOP-I9L9IHO' # Specify the name of your self-hosted agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
